# Paycom Automation Configuration

# Copy this file to config.py and fill in local values before running.

# Your Paycom PIN.
PIN = ""

# Paycom time clock URL.
PAYCOM_URL = "https://www.paycomonline.net/v4/ee/web.php/timeclock/WEB04"
PAYCOM_HOURS_URL = "https://www.paycomonline.net/v4/ee/web.php/timecard/WEB02#!timecard-view"
PAYCOM_DRY_RUN = True

# Slack Automation Configuration
SLACK_CHANNEL_URL_PROD = ""
SLACK_CHANNEL_URL_TEST = ""
SLACK_CHANNEL_URL = SLACK_CHANNEL_URL_PROD
SLACK_FORCE_HEADLESS = False

# Day-specific messages (Sunday-Saturday).
SLACK_MESSAGE_IN_SUNDAY = "signing on"
SLACK_MESSAGE_IN_SUNDAY_ALTERNATE = ""
SLACK_MESSAGE_IN_SUNDAY_ALTERNATE_ENABLED = False
SLACK_MESSAGE_OUT_SUNDAY = "signing off"
SLACK_MESSAGE_OUT_SUNDAY_ALTERNATE = ""
SLACK_MESSAGE_OUT_SUNDAY_ALTERNATE_ENABLED = False

SLACK_MESSAGE_IN_MONDAY = "signing on"
SLACK_MESSAGE_IN_MONDAY_ALTERNATE = ""
SLACK_MESSAGE_IN_MONDAY_ALTERNATE_ENABLED = False
SLACK_MESSAGE_OUT_MONDAY = "signing off"
SLACK_MESSAGE_OUT_MONDAY_ALTERNATE = ""
SLACK_MESSAGE_OUT_MONDAY_ALTERNATE_ENABLED = False

SLACK_MESSAGE_IN_TUESDAY = "signing on"
SLACK_MESSAGE_IN_TUESDAY_ALTERNATE = ""
SLACK_MESSAGE_IN_TUESDAY_ALTERNATE_ENABLED = False
SLACK_MESSAGE_OUT_TUESDAY = "signing off"
SLACK_MESSAGE_OUT_TUESDAY_ALTERNATE = ""
SLACK_MESSAGE_OUT_TUESDAY_ALTERNATE_ENABLED = False

SLACK_MESSAGE_IN_WEDNESDAY = "signing on"
SLACK_MESSAGE_IN_WEDNESDAY_ALTERNATE = ""
SLACK_MESSAGE_IN_WEDNESDAY_ALTERNATE_ENABLED = False
SLACK_MESSAGE_OUT_WEDNESDAY = "signing off"
SLACK_MESSAGE_OUT_WEDNESDAY_ALTERNATE = ""
SLACK_MESSAGE_OUT_WEDNESDAY_ALTERNATE_ENABLED = False

SLACK_MESSAGE_IN_THURSDAY = "signing on"
SLACK_MESSAGE_IN_THURSDAY_ALTERNATE = ""
SLACK_MESSAGE_IN_THURSDAY_ALTERNATE_ENABLED = False
SLACK_MESSAGE_OUT_THURSDAY = "signing off"
SLACK_MESSAGE_OUT_THURSDAY_ALTERNATE = ""
SLACK_MESSAGE_OUT_THURSDAY_ALTERNATE_ENABLED = False

SLACK_MESSAGE_IN_FRIDAY = "signing on"
SLACK_MESSAGE_IN_FRIDAY_ALTERNATE = ""
SLACK_MESSAGE_IN_FRIDAY_ALTERNATE_ENABLED = False
SLACK_MESSAGE_OUT_FRIDAY = "signing off"
SLACK_MESSAGE_OUT_FRIDAY_ALTERNATE = ""
SLACK_MESSAGE_OUT_FRIDAY_ALTERNATE_ENABLED = False

SLACK_MESSAGE_IN_SATURDAY = "signing on"
SLACK_MESSAGE_IN_SATURDAY_ALTERNATE = ""
SLACK_MESSAGE_IN_SATURDAY_ALTERNATE_ENABLED = False
SLACK_MESSAGE_OUT_SATURDAY = "signing off"
SLACK_MESSAGE_OUT_SATURDAY_ALTERNATE = ""
SLACK_MESSAGE_OUT_SATURDAY_ALTERNATE_ENABLED = False

# Day-specific lunch messages (Sunday-Saturday).
SLACK_MESSAGE_LUNCH_SUNDAY = "breaking"
SLACK_MESSAGE_BACK_SUNDAY = "back"
SLACK_MESSAGE_LUNCH_MONDAY = "breaking"
SLACK_MESSAGE_BACK_MONDAY = "back"
SLACK_MESSAGE_LUNCH_TUESDAY = "breaking"
SLACK_MESSAGE_BACK_TUESDAY = "back"
SLACK_MESSAGE_LUNCH_WEDNESDAY = "breaking"
SLACK_MESSAGE_BACK_WEDNESDAY = "back"
SLACK_MESSAGE_LUNCH_THURSDAY = "breaking"
SLACK_MESSAGE_BACK_THURSDAY = "back"
SLACK_MESSAGE_LUNCH_FRIDAY = "breaking"
SLACK_MESSAGE_BACK_FRIDAY = "back"
SLACK_MESSAGE_LUNCH_SATURDAY = "breaking"
SLACK_MESSAGE_BACK_SATURDAY = "back"

# Work Clock In/Out Configuration
WORK_CLOCK_STATE_FILE = "work_hours.json"
WORK_CLOCK_BREAK_MINUTES = 30
WORK_CLOCK_BREAK_APPLIES_AFTER_HOURS = 4.0
WORK_CLOCK_CAPPED = True
WORK_CLOCK_CAP_HOURS = 42.5
WORK_CLOCK_DEFAULT_DAILY_HOURS = 8.0
WORK_CLOCK_AUTO_OUT_MAX_HOURS = 24.0
WORK_CLOCK_RESET_ON_FRIDAY_CLOCK_OUT = True
WORK_CLOCK_SYNC_FROM_PAYCOM = True
WORK_CLOCK_SYNC_BEFORE_CLOCK_IN = True
WORK_CLOCK_SYNC_AFTER_CLOCK_OUT = True

PAYCOM_WEEK_HOURS_REGEX_PATTERNS = [
    r"(?:weekly\s*totals?|week\s*totals?|this\s*week|week\s*total|total\s*hours?)\s*[:\-]?\s*(\d{1,3}(?:\.\d{1,2})?)",
    r"(?:pay\s*period\s*totals?)\s*[:\-]?\s*(\d{1,3}(?:\.\d{1,2})?)",
    r"(\d{1,3}(?:\.\d{1,2})?)\s*(?:hrs?|hours?)\s*(?:this\s*week|week\s*total|weekly\s*totals?)",
]

# CRM Automation Configuration
CRM_USERNAME = ""
CRM_PASSWORD = ""

CRM_LOGIN_URL = "https://crm2.legacy.printfly.com/login"
CRM_LOCKED_URL = ""
CRM_SHIPPING_FREE_URL = ""
CRM_SHIPPING_RUSH_URL = ""
CRM_SHIPPING_ALL_URL = ""
CRM_ORDER_GOODS_RUSH_URL = ""
CRM_SHIPPING_BYPASS_URL = ""
SANMAR_URL = "https://www.sanmar.com/"
SANMAR_CART_URL = "https://www.sanmar.com/cart"
SANMAR_PROFILE_DIR = "chrome_profile"
CRM_SHIPPING_URL = CRM_SHIPPING_FREE_URL
CRM_SHIPPING_FILTER_DEFAULT = "free"

CRM_HEADLESS = True
CRM_ALLOW_VISIBLE_FALLBACK = False
CRM_PROFILE_DIR = "chrome_profile_crm"
CRM_PAGE_LOAD_TIMEOUT = 30
CRM_ACTION_TIMEOUT = 15
CRM_MAX_RETRIES = 1
CRM_RETRY_DELAY_SECONDS = 3
CRM_DRY_RUN = True
CRM_AUTO_SPLITTER_PREFLIGHT_REUSE_SECONDS = 600

# Screenshot policy.
AUTOMATION_SCREENSHOTS_ON_SUCCESS = False
AUTOMATION_SCREENSHOTS_ON_FAILURE = True
AUTOMATION_DEBUG_SCREENSHOTS = False

# CRM auto-splitter settings.
PROCESSOR_LOGIN_URL = CRM_LOGIN_URL
PROCESSOR_LIST_URL = ""
PRODUCT_SEPARATOR_LIST_URL_FREE = ""
PRODUCT_SEPARATOR_LIST_URL_RUSH = ""
PRODUCT_SEPARATOR_LIST_URL_ALL = ""
PRODUCT_SEPARATOR_DEFAULT_LIST_MODE = "all"
PRODUCT_SEPARATOR_LIST_URL = PRODUCT_SEPARATOR_LIST_URL_ALL
PROCESSOR_ORDER_URL_TEMPLATE = "https://crm2.legacy.printfly.com/order/{order_id}"
PROCESSOR_PROFILE_DIR = CRM_PROFILE_DIR
PROCESSOR_HEADLESS = CRM_HEADLESS
PROCESSOR_PAGE_LOAD_TIMEOUT = CRM_PAGE_LOAD_TIMEOUT
PROCESSOR_ACTION_TIMEOUT = CRM_ACTION_TIMEOUT
PROCESSOR_DRY_RUN = True
